### ISSUE TITLE
Use of @ForIntent

### ISSUE THREAD

**Issue by Priyankachaudhary2606** [actions-on-google/dialogflow-helper-intents-java#1]
In the project, how the control has passed to @ForIntent. Which class is defining this intents to be registered.
I want to understand the normal flow of the project code.

**Comment by taycaldwell** [comment]
Hi @Priyankachaudhary2606,

When you deploy the project to App Engine, the [ActionsServlet.java](https://github.com/actions-on-google/dialogflow-helper-intents-java/blob/master/src/main/java/com/example/ActionsServlet.java) class is used as the entry point, and will handle all requests made to your fulfillment.

This class has a member variable that is assigned to an instance of the [HelperIntentsApp.java](https://github.com/actions-on-google/dialogflow-helper-intents-java/blob/master/src/main/java/com/example/HelperIntentsApp.java) class. Upon an incoming POST request to your fulfillment endpoint, the [doPost](https://github.com/actions-on-google/dialogflow-helper-intents-java/blob/master/src/main/java/com/example/ActionsServlet.java#L44) method of ActionsServlet is called. This method then passes the body to the [handleRequest](https://github.com/actions-on-google/dialogflow-helper-intents-java/blob/master/src/main/java/com/example/ActionsServlet.java#L49) method of HelperIntentsApp. The handleRequest method will then [check the annotations](https://github.com/actions-on-google/actions-on-google-java/blob/master/src/main/kotlin/com/google/actions/api/DefaultApp.kt#L71) of every method in HelperIntentsApp and check to see if the intent name matches the intent name specified in the request. If there is such a method, it will invoke that method and return the resulting JSON response.

**Comment by Priyankachaudhary2606** [comment]
Thanks for the help, @taycaldwell .
So nice of you.

**Comment by taycaldwell** [comment]
No problem. Please open a new issue if you have any other questions or issues.
